name: Feed
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
      - test

jobs:
  starred-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install feedle
        run: go install github.com/toga4/feedle/cmd/feedle@main

      - run: mkdir -p dist

      - name: Generate releases feed url from starred repositories
        run: gh api 'users/toga4/starred?per_page=1000' | jq -r ".[] | .full_name" | xargs -IZZ -n 1 echo "https://github.com/ZZ/releases.atom" > feed.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate releases feed from starred repositories
        run: feedle -title "Releases from Starred by toga4" -link https://toga4.github.io/feeds/starred-releases.atom < feed.txt > dist/starred-releases.atom

      - name: Upload feed as artifact
        uses: actions/upload-artifact@v4
        with:
          name: starred-releases
          path: dist/starred-releases.atom
          retention-days: 1

  weneedfeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r7kamura/weneedfeed-action@v3
        with:
          base_url: https://toga4.github.io/feeds/weneedfeed

      - name: Upload feed as artifact
        uses: actions/upload-artifact@v4
        with:
          name: weneedfeed
          path: output
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs:
      - starred-releases
      - weneedfeed
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List all files
        run: find ./dist

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
