name: Feed
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  feed:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install feedle
        run: go install github.com/toga4/feedle/cmd/feedle@latest

      - run: mkdir -p dist

      - name: Generate releases feed url from starred repositories
        run: gh api 'users/toga4/starred?per_page=1000' | jq -r ".[] | .full_name" | xargs -IZZ -n 1 echo "https://github.com/ZZ/releases.atom" > feed.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate releases feed from starred repositories
        run: feedle -title "Releases from Starred by toga4" -link https://toga4.github.io/feeds/starred-releases.atom < feed.txt > dist/starred-releases.atom

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
