name: Feed
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  feed:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install gsrf
        run: go install github.com/toga4/github-stars-release-feeder/cmd/gsrf@latest

      - run: mkdir -p dist

      - name: Generate releases feed from starred repositories
        run: gsrf -user toga4 -link https://toga4.github.io/feeds/starred-releases.atom > dist/starred-releases.atom

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
